controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
api_clients_post:
    path: /api/clientspost
    controller: App\Controller\ClientController::createClient
    methods: ['POST']

api_articles_post:
    path: /api/articlespost
    controller: App\Controller\ArticleController::createArticle
    methods: ['POST']
